# Generated by Django 2.1 on 2020-06-18 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flag_icon', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(max_length=15000)),
                ('brand_selector', models.CharField(max_length=100)),
                ('country_selector', models.CharField(blank=True, max_length=100, null=True)),
                ('description_selector', models.CharField(blank=True, max_length=100, null=True)),
                ('crawled', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='origin_country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Country'),
        ),
    ]
