# Generated by Django 2.2 on 2020-06-18 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlconfig',
            name='user_agent',
            field=models.CharField(blank=True, default='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0', max_length=10000, null=True),
        ),
    ]
