# Generated by Django 2.2 on 2020-06-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=150)),
                ('message', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='logo',
            field=models.URLField(blank=True, max_length=10000, null=True),
        ),
    ]
