# Generated by Django 2.2 on 2020-06-18 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_crawlconfig_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='origin_country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Country'),
        ),
    ]
